### TOP_DIR: The Ddirectory containing the .bsv file
### TOP_FILE: The Name of the file that contains the topmost module
### TOP_MODULE: The Name of the topmost module which will be defined inside the TOP_FILE
### MODULE: This is the name of the python test bench WITHOUT the (.py) extension


TOP_MODULE:=mkChainL1Noc
TOP_FILE:=ChainNocL1.bsv
TOP_DIR:=.
MODULE:=testRunner
BLUESPEC_TOOL:=/home/abi/tools/bsc

